services:
  - type: web
    name: smarthire-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash startup.sh
    envVars:
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_USERNAME
        value: ""
      - key: MAIL_PASSWORD
        value: ""
      - key: TELEGRAM_TOKEN
        value: ""
